version: "3"
services:
  nuxt:
    build:
      context: ./docker/nuxt
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./front:/home/node/app/front
    working_dir: /home/node/app/front
    tty: true
    command: sh -c "yarn dev"
    environment:
      - HOST=0.0.0.0
    networks:
      - app-net

  go:
    build:
      context: ./docker/go
    container_name: backend
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: fresh
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
