version: "3"
services:
  nuxt:
    build:
      context: ./docker/nuxt
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./front:/home/node/app/front
    working_dir: /home/node/app/front
    tty: true
    command: sh -c "yarn dev"
    environment:
      - HOST=0.0.0.0
    networks:
      - app-net

  go:
    build:
      context: ./docker/go
    container_name: backend
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: fresh
    networks:
      - app-net
    links:
      - db

  db:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ADDRESS:
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
